# Generated by Django 2.2.4 on 2019-08-30 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscription', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_num', models.CharField(db_index=True, max_length=9, unique=True, verbose_name='Номер автомобиля')),
                ('is_active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('delete_date', models.DateTimeField(blank=True, null=True, verbose_name='Удален')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_date', models.DateTimeField(auto_now_add=True)),
                ('subscription_date_validation', models.DateTimeField(default=None)),
                ('is_active', models.BooleanField(default=True)),
                ('reg_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.Car', verbose_name='Номер автомобиля')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.Subscription', verbose_name='Тарифный план')),
            ],
            options={
                'verbose_name': 'Подписка автомобиля',
                'verbose_name_plural': 'Подписки автомобиля',
            },
        ),
    ]
