# Generated by Django 2.2.4 on 2019-08-29 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.CreateModel(
            name='SubscriptionCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_date', models.DateTimeField(auto_now_add=True)),
                ('subscription_date_validation', models.DateTimeField(default=None)),
                ('is_active', models.BooleanField(default=True)),
                ('reg_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.Car', verbose_name='Номер автомобиля')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.Subscription', verbose_name='Тарифный план')),
            ],
            options={
                'verbose_name': 'Подписка автомобиля',
                'verbose_name_plural': 'Подписки автомобиля',
            },
        ),
    ]
