# Generated by Django 2.2.4 on 2019-09-10 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardBankUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('payment_id', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='id оплаты')),
                ('last4', models.CharField(blank=True, max_length=4, null=True, verbose_name='Последние 4 цифры карты')),
                ('card_type', models.CharField(blank=True, max_length=35, null=True, verbose_name='Тип платежной системы')),
                ('bank', models.CharField(blank=True, max_length=50, null=True, verbose_name='Банк')),
            ],
        ),
        migrations.CreateModel(
            name='OrderBankUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('update', models.DateTimeField(auto_now=True, null=True, verbose_name='Изменили')),
                ('is_regular_pay', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('error', models.CharField(blank=True, max_length=10, null=True, verbose_name='Ошибка')),
                ('error_description', models.CharField(blank=True, max_length=15, null=True, verbose_name='Описание ошибок')),
                ('payment_method_saved', models.BooleanField(default=False)),
                ('recipient_account_id', models.CharField(blank=True, max_length=15, null=True, verbose_name='account_id')),
                ('recipient_gateway_id', models.CharField(blank=True, max_length=15, null=True, verbose_name='gateway_id')),
                ('refundable', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, max_length=20, null=True, verbose_name='Статус платежа')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Запрос на оплату')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='car.Car', verbose_name='Машина')),
                ('card_bank_users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_cards_bank_users', to='payment.CardBankUsers', verbose_name='Какой картой оплачивали')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='subscription.Subscription', verbose_name='Подписка')),
            ],
        ),
        migrations.CreateModel(
            name='BankUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('card_bank_users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards_bank_users', to='payment.CardBankUsers', verbose_name='Банковские данные пользователя')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
