# Generated by Django 2.2.4 on 2019-08-30 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car', '0001_initial'),
        ('subscription', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Washing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('washing', models.CharField(max_length=20, verbose_name='Комментарий к помывке')),
                ('is_active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.Car', verbose_name='Автомобиль')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('wash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.Wash', verbose_name='Помывка')),
            ],
            options={
                'verbose_name': 'Помывка',
                'verbose_name_plural': 'Помывки',
            },
        ),
    ]
