# Generated by Django 2.2.4 on 2019-09-10 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, unique=True, verbose_name='Город')),
                ('is_active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('delete_date', models.DateTimeField(blank=True, null=True, verbose_name='Удален')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Wash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=150, unique=True, verbose_name='Адрес')),
                ('is_active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('delete_date', models.DateTimeField(blank=True, null=True, verbose_name='Удален')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.City', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Мойка',
                'verbose_name_plural': 'Мойки',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription', models.CharField(max_length=45, unique=True, verbose_name='Тарифный план')),
                ('is_active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('delete_date', models.DateTimeField(blank=True, null=True, verbose_name='Удален')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='subscription.City', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Тарифный план',
                'verbose_name_plural': 'Тарифные планы',
            },
        ),
        migrations.CreateModel(
            name='Sevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sevice', models.CharField(max_length=45, unique=True, verbose_name='Имя услуги')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Цена услуги')),
                ('is_active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('delete_date', models.DateTimeField(blank=True, null=True, verbose_name='Удален')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sevices_subscription', to='subscription.Subscription', verbose_name='Тарифный план')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
