# Generated by Django 2.2.4 on 2019-09-03 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sevice',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='subscription.Subscription', verbose_name='Тарифный план'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='subscription.City', verbose_name='Город'),
        ),
    ]
